# Generated by Django 4.2 on 2026-05-01 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship_test', '0006_scholarshiptestattempt_portal_student_and_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankPredictorLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_otp_requested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scholarship_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rank_predictor_leads', to='scholarship_test.scholarshipstudent')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
