# Generated by Django 4.2 on 2026-04-22 07:14

from django.db import migrations, models
import teacherschedule.models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherschedule', '0004_scheduleentry_source_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedschedule',
            name='file',
            field=models.FileField(upload_to=teacherschedule.models.uploaded_schedule_path),
        ),
    ]
