# Generated by Django 4.2 on 2026-04-24

from django.db import migrations, models


def populate_student_username(apps, schema_editor):
    Student = apps.get_model("sds", "Student")
    for student in Student.objects.select_related("user").all():
        username = getattr(student.user, "username", "") or ""
        if student.username != username:
            student.username = username
            student.save(update_fields=["username"])


class Migration(migrations.Migration):

    dependencies = [
        ("sds", "0019_teacheradmin_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="username",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.RunPython(populate_student_username, migrations.RunPython.noop),
    ]
